In [3]:
import numpy as np

In [3]:
k = np.array([73, 67, 43])
k

array([73, 67, 43])

In [6]:
w1=0.3
w2= 0.2
w3=0.6
weights = np.array([w1, w2, w3])
weights

array([0.3, 0.2, 0.6])

In [9]:
type(weights)

numpy.ndarray

In [10]:
np.dot(k, weights)
(k*weights).sum()

np.float64(61.099999999999994)

In [14]:
#lists 
arr1= list(range(100000))
arr2= list(range(100000, 200000))

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1 + x2
print(result) 


19999900000
CPU times: total: 46.9 ms
Wall time: 446 ms


In [17]:
%%time
np.dot(arr1, arr2)

CPU times: total: 15.6 ms
Wall time: 36 ms


np.int64(833323333350000)

In [19]:
climate_data = np.array([[23, 24, 25], 
                         [11, 15, 13],
                         [4, 8, 9],
                         [90, 96, 82]])
#delimiter=, or : --- reprsets how the data us sepetrated
#skip_header=1, 2for not counting the heaidngs for each column
climate_data

array([[23, 24, 25],
       [11, 15, 13],
       [ 4,  8,  9],
       [90, 96, 82]])

In [24]:
yields = climate_data@weights
print(yields)
yields.shape

[26.7 14.1  8.2 95.4]


(4,)

In [30]:
np.savetxt('climate_data.txt', climate_data, fmt='%.02f', header= 'temp, rain, yeild_apples')

operations are:
np.sum
np.exp
np.round
np.reshape
np.stack
np.concantete
np.split
np.dot
np.transpose
np.eigvals
np.mean
np.median
np.std
np.max

ARTIHEMTAIC OPERATIONS:

In [4]:
arr1= np.array([[1, 2, 3, 4], [5,6,7,8], [9, 10, 11,12]])
arr2= np.array([[10, 20, 30, 47], [51,62,74,85], [91, 103, 19,10]])

In [5]:
print(arr1+ arr2)
print(arr1+3)
print(arr2/2)
arr1.shape

[[ 11  22  33  51]
 [ 56  68  81  93]
 [100 113  30  22]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5.  10.  15.  23.5]
 [25.5 31.  37.  42.5]
 [45.5 51.5  9.5  5. ]]


(3, 4)

In [6]:
import numpy as np

# Define two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate their sum
result = arr1 + arr2

# Print the result
print("Sum of arr1 and arr2:", result)


Sum of arr1 and arr2: [5 7 9]


replication is  possible if one of  numbemr of shape matches any dimensions 
arr.shape

In [18]:
print(arr1==arr2)
print(arr1<=arr2)
(arr1==arr2).dtype

[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]]


dtype('bool')

In [9]:
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]  
    
])
arr3.shape
#it is 0 indexing

(3, 3, 3)

In [12]:
element = arr3d[1, 2, 1] 
print("Accessed Element:", element)

range_elements = arr3d[1, 1:2, :]
print("Accessed Range of Elements:", range_elements)


Accessed Element: 17
Accessed Range of Elements: [[13 14 15]]


In [17]:
print(np.zeros((3,2)))
print(" ")
print(np.ones((2,3,2)))
print(" ")
print(np.eye(3))



[[0. 0.]
 [0. 0.]
 [0. 0.]]
 
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
random_numbers = np.random.rand(5)
print(random_numbers)

[0.48879938 0.63677045 0.48923183 0.18015575 0.46251958]


In [28]:
##fixed value 
print(np.full([2,3], 23))

#range with start stop and step of the range
print(np.arange(10, 90, 3))
np.arange(10, 90, 3).shape
print(np.arange(10, 90, 3).reshape(3,3,3))

#equally spaced
print(np.linspace(3, 27,6))


[[23 23 23]
 [23 23 23]]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88]
[[[10 13 16]
  [19 22 25]
  [28 31 34]]

 [[37 40 43]
  [46 49 52]
  [55 58 61]]

 [[64 67 70]
  [73 76 79]
  [82 85 88]]]
[ 3.   7.8 12.6 17.4 22.2 27. ]


### Advanced NumPy Examples

#### Element-wise Functions

In [ ]:

# Element-wise mathematical operations
arr = np.array([1, 4, 9, 16, 25])
print("Square Root:", np.sqrt(arr))
print("Logarithm:", np.log(arr))
print("Sine:", np.sin(arr))
    

#### Aggregate Functions

In [ ]:

# Aggregate operations on an array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Max Element:", np.max(arr))
print("Index of Max Element:", np.argmax(arr))
    

#### Sorting and Searching

In [ ]:

# Sorting and searching in arrays
arr = np.array([10, 5, 8, 1, 3])
print("Sorted Array:", np.sort(arr))
print("Indices of Sorted Elements:", np.argsort(arr))
print("Indices where value > 5:", np.where(arr > 5))
    

#### Linear Algebra

In [ ]:

# Linear algebra operations
matrix = np.array([[4, 2], [3, 1]])
print("Determinant:", np.linalg.det(matrix))
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)
    

#### Random Sampling

In [ ]:

# Generating random numbers
print("Random Integers:", np.random.randint(1, 10, size=5))
print("Random Normal Distribution:", np.random.normal(0, 1, size=5))
print("Random Choice:", np.random.choice([10, 20, 30, 40], size=3))
    

#### Statistical Operations

In [ ]:

# Statistical operations
arr = np.array([10, 20, 30, 40, 50])
print("Variance:", np.var(arr))
print("25th Percentile:", np.percentile(arr, 25))
print("Median:", np.median(arr))
    

#### Practical Example: Data Normalization

In [ ]:

# Data normalization example
data = np.array([50, 20, 30, 80, 100])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized Data:", normalized_data)
    

#### Practical Example: Monte Carlo Simulation

In [ ]:

# Monte Carlo simulation to estimate the value of pi
num_points = 10000
x = np.random.rand(num_points)
y = np.random.rand(num_points)
inside_circle = (x**2 + y**2) <= 1
pi_estimate = (np.sum(inside_circle) / num_points) * 4
print("Estimated Value of Pi:", pi_estimate)
    